movielistproject/movielistapp/urls.py
from . import views
from django.urls import path
app_name='movielistapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movielistproject/movielistproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movielistapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movielistproject/movielistapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):

    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movielistproject/movielistapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movielistproject/movielistapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import  MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }

    return render(request,"index.html",context)
def detail(request,movie_id):
    movie= Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img= request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')

    return render(request,"add.html")
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None ,request.FILES,instance=movie)
    if form .is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movielistproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<input type="text" name="name" placeholder="enter a movie name">
<input type="text" name="desc"placeholder="enter the movie description">
<input type="text" name="year" placeholder="enter movie year">
 <input type="file" name="img">
  <input type="submit">
</form>
{% endblock %}

movielistproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark nav-bar-top">
  <a class="navbar-brand" href="#">

    MOVIELIST PLATFORM
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movielistproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    are bu ant to delete this movie
    <input type="submit">
</form>

movielistproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="200" height="200">

        </div>

<div class="col-md-6">

    <h4>{{movie.name}}</h4>
    <h6>{{movie.desc}}</h6>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movielistapp:update'  movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movielistapp:delete'  movie.id %}">delete</a>

</div>

  </div>
</div>

{% endblock %}

movielistproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movielistproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid p-0 m-0
				align-items-center
				justify-content-center d-flex"
			style="min-height: 100vh;
			background-color: #808080;">

		<!-- Row for the card-->
		<div class="row w-100 p-0 w-0">
        {% for i in movie_list %}
			<!-- Column for card-->
			<div class="col-lg-4 mb-2">
				<div class="card mx-auto" style="width:18rem;">
                    <img class="card-img-top" src="{{i.img.url}}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">{{i.name}}</h4>
                      <p class="card-text">{{i.desc}}</p>
                      <a href="{% url 'movielistapp:detail' i.id %}" class="btn btn-primary">go somewhere </a>

  </div>
</div>

        </div>

        {% endfor %}
            <div style="width:8000px;" align="right">

             <a href="{% url 'movielistapp:add_movie'   %}" class="btn btn-primary " >add movies </a>
     </div>

    </div>
</div>
{% endblock %}